function control_input = controller_pid(pid1, pid2, e_theta, e_theta_dot, e_theta_inte, gravity)
    control_input(1) = pid1.p*e_theta(1) ...
                + pid1.d*e_theta_dot(1) ...
                + pid1.i*e_theta_inte(1) ...
                + gravity(1);
    control_input(2) = pid2.p*e_theta(2) ...
                + pid2.d*e_theta_dot(2) ...
                + pid2.i*e_theta_inte(2) ...
                + gravity(2);
end
